#!/bin/bash

mkdir /images
mount /dev/disk/by-label/IMAGES /images -o ro -t ntfs


if [[ ! -z $isdebug ]]; then
    echo "DEBUG MODE"
    echo "(Exit bash to continue)"
    bash
fi

if [ ! -e /dev/sdb  ] &&  [ ! -e /dev/nvme0n1 ]; then
    if [[ ! -z $isdebug ]]; then
        echo "No disk found. Take care..."
    else
        echo "No disk found. Cannot continue..."
        exit 1
    fi
fi

cd /images
echo "Select image to restore:"
select d in $(ls -1dN -- */ | grep -v "System Volume Information" | grep -v  "^\\$"); do test -n "$d" && break; echo ">>> Invalid Selection"; done

if [[ -z $d ]]; then
    echo "No image found. Cannot continue..."
    exit 1
fi

export img=$(basename $d)

export type=down
export imgType=n
export osid=9  # Windows 10, check /usr/share/fog/lib/funcs.sh for values
export imgFormat=5
export imgPartitionType=all

if [[ -f "custom.sh" ]]; then
    source custom.sh
fi
if [[ -f "$img/custom.sh" ]]; then
    source $img/custom.sh
fi

fog.download

if [[ -z $isdebug ]]; then
    echo "##############################################################################"
    echo "#                                                                            #"
    echo "#                      Computer will reboot in 1 minute                      #"
    echo "#                                                                            #"
    echo "##############################################################################"
    usleep 60000000
    reboot
    exit 0
fi

echo "fog.download finished! (Exit bash to reboot)"
bash
reboot
